name: deliverytak
description: "Deliverytak is a Flutter application integrated with Firebase backend services, designed to serve as a fashion store with an intuitive admin panel. It allows users to browse through a variety of fashion items, add them to their cart, and make purchases seamlessly. Additionally, it empowers administrators to manage product listings, orders, and user data efficiently."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10
  firebase_messaging: ^14.8.2

  flutter_bootstrap5: ^1.1.1+1
  get: ^4.6.5
  flutter_local_notifications: ^17.1.0
  phone_input: ^1.0.0
  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.1.12
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  image_picker: ^1.0.2
  flutter_map: ^6.1.0
  geolocator: ^11.0.0
  syncfusion_flutter_charts: ^25.1.38
  flex_color_picker: ^3.4.1
  barcode_widget: ^2.0.4
  simple_barcode_scanner: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/favicon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/favicon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/favicon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter:

  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
        
    - family: Breathing
      fonts:
        - asset: assets/fonts/Breathing.ttf